name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      # - uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - run: pnpm install

      - run: pnpm build

      - uses: actions/upload-artifact@v3
        with:
          path: apps/extension/dist/*
